version: '2'
services:
  configserver:
    image: example/confsvr:section12
    ports:
       - "8888:8888"
  database:
    image: postgres:9.5
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "123abc"
      POSTGRES_DB:       "postgres"
  cargoservice:
    image: example/cargo-service:section12
    ports:
      - "8080:8080"
    environment:
      PROFILE: "prod"
      CONFIGSERVER_URI: "http://configserver:8888"
      CONFIGSERVER_PORT:   "8888"
      DATABASESERVER_PORT: "5432"
#    depends_on:
#      - configserver
#      - database
