####################################
server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/tzs919/config.git
          searchPaths: cargoservice
#          username: tzs919
#          password: 123456


####################################
#server:
#   port: 8888
#spring:
#  profiles:
#    active: native
#  cloud:
#     config:
#       server:
#         native:
##              searchLocations: file://
#           searchLocations: classpath:config/cargoservice
